### ISSUE TITLE
Is it possible to run iLearnPlus on terminal with threads ?

### ISSUE THREAD

**Issue by ankushkumarbansal** [Superzchen/iLearnPlus#5]
I wish to perform parallel computing on large dataset using AWS (either EC2 instance or sagemaker) . Is there any way to  scale iLearnPlus on large dataset for fast processing ?
Thanks you for developing this wonderful package.

**Comment by Superzchen** [comment]
Thank you for your interest in our work.
In current version of iLearnPlus, only part algorithms (such as RF, LightGBM, XGBoost, Bagging) support parallel computing and it only can be run with GUI. In the furture version, we will consider to support capabilities such as command line and parallel computing in later version.

**Comment by Superzchen** [comment]
> 
> 
> I wish to perform parallel computing on large dataset using AWS (either EC2 instance or sagemaker) . Is there any way to scale iLearnPlus on large dataset for fast processing ?
> Thanks you for developing this wonderful package.

Thank you for your interest in our work.
In current version of iLearnPlus, only part algorithms (such as RF, LightGBM, XGBoost, Bagging) support parallel computing and it only can be run with GUI. In the furture version, we will consider to support capabilities such as command line and parallel computing in later version.
